### ISSUE TITLE
Install dependencies error: sollya with python3.8.10

### ISSUE THREAD

**Issue by hbrunie** [metalibm/metalibm#107]
```
 ~/github/metalibm
 >> pip install -r requirements.txt 
Collecting git+https://gitlab.com/metalibm-dev/pythonsollya (from -r requirements.txt (line 4))
  Cloning https://gitlab.com/metalibm-dev/pythonsollya to /tmp/pip-req-build-1zndcudd
  Running command git clone -q https://gitlab.com/metalibm-dev/pythonsollya /tmp/pip-req-build-1zndcudd
    ERROR: Command errored out with exit status 1:
     command: /home/hbrunie/github/metalibm/.venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-1zndcudd/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-1zndcudd/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-1zndcudd/pip-egg-info
         cwd: /tmp/pip-req-build-1zndcudd/
    Complete output (76 lines):
    running egg_info
    creating /tmp/pip-req-build-1zndcudd/pip-egg-info/sollya.egg-info
    writing /tmp/pip-req-build-1zndcudd/pip-egg-info/sollya.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-req-build-1zndcudd/pip-egg-info/sollya.egg-info/dependency_links.txt
    writing requirements to /tmp/pip-req-build-1zndcudd/pip-egg-info/sollya.egg-info/requires.txt
    writing top-level names to /tmp/pip-req-build-1zndcudd/pip-egg-info/sollya.egg-info/top_level.txt
    writing manifest file '/tmp/pip-req-build-1zndcudd/pip-egg-info/sollya.egg-info/SOURCES.txt'
    PATH="/usr/local:/home/hbrunie/github/metalibm/.venv/bin:/home/hbrunie/usr/bin/:/home/hbrunie/gitlab/parioopt/venv/bin:/home/hbrunie/usr/bin/:/home/hbrunie/.local/bin:/home/hbrunie/.cargo/bin:/home/hbrunie/usr/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin" python3 gen_func.py > sollya_func.pxi
    Traceback (most recent call last):
      File "gen_func.py", line 272, in <module>
        print(func.generate_binding())
      File "gen_func.py", line 149, in generate_binding
        return declaration + self.docstring() + code_op_decl + code_clear + code_ret
      File "gen_func.py", line 83, in docstring
        interpreter = Popen(['sollya'], stdin=PIPE, stdout=PIPE,
      File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'sollya'
    make: *** [GNUmakefile:39: sollya_func.pxi] Error 1
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-1zndcudd/setup.py", line 55, in <module>
        setuptools.setup(
      File "/home/hbrunie/github/metalibm/.venv/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/hbrunie/github/metalibm/.venv/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 296, in run
        self.find_sources()
      File "/home/hbrunie/github/metalibm/.venv/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 303, in find_sources
        mm.run()
      File "/home/hbrunie/github/metalibm/.venv/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 534, in run
        self.add_defaults()
      File "/home/hbrunie/github/metalibm/.venv/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 570, in add_defaults
        sdist.add_defaults(self)
      File "/usr/lib/python3.8/distutils/command/sdist.py", line 228, in add_defaults
        self._add_defaults_ext()
      File "/usr/lib/python3.8/distutils/command/sdist.py", line 311, in _add_defaults_ext
        build_ext = self.get_finalized_command('build_ext')
      File "/usr/lib/python3.8/distutils/cmd.py", line 299, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "/usr/lib/python3.8/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/tmp/pip-req-build-1zndcudd/setup.py", line 50, in finalize_options
        self.distribution.ext_modules[:] = cythonize(
      File "/tmp/pip-req-build-1zndcudd/.eggs/Cython-0.29.26-py3.8-linux-x86_64.egg/Cython/Build/Dependencies.py", line 966, in cythonize
        module_list, module_metadata = create_extension_list(
      File "/tmp/pip-req-build-1zndcudd/.eggs/Cython-0.29.26-py3.8-linux-x86_64.egg/Cython/Build/Dependencies.py", line 830, in create_extension_list
        kwds = deps.distutils_info(file, aliases, base).values
      File "/tmp/pip-req-build-1zndcudd/.eggs/Cython-0.29.26-py3.8-linux-x86_64.egg/Cython/Build/Dependencies.py", line 685, in distutils_info
        return (self.transitive_merge(filename, self.distutils_info0, DistutilsInfo.merge)
      File "/tmp/pip-req-build-1zndcudd/.eggs/Cython-0.29.26-py3.8-linux-x86_64.egg/Cython/Build/Dependencies.py", line 694, in transitive_merge
        return self.transitive_merge_helper(
      File "/tmp/pip-req-build-1zndcudd/.eggs/Cython-0.29.26-py3.8-linux-x86_64.egg/Cython/Build/Dependencies.py", line 700, in transitive_merge_helper
        deps = extract(node)
      File "/tmp/pip-req-build-1zndcudd/.eggs/Cython-0.29.26-py3.8-linux-x86_64.egg/Cython/Build/Dependencies.py", line 665, in distutils_info0
        cimports, externs, incdirs = self.cimports_externs_incdirs(filename)
      File "/tmp/pip-req-build-1zndcudd/.eggs/Cython-0.29.26-py3.8-linux-x86_64.egg/Cython/Utils.py", line 55, in wrapper
        res = cache[args] = f(self, *args)
      File "/tmp/pip-req-build-1zndcudd/.eggs/Cython-0.29.26-py3.8-linux-x86_64.egg/Cython/Build/Dependencies.py", line 553, in cimports_externs_incdirs
        for include in self.included_files(filename):
      File "/tmp/pip-req-build-1zndcudd/.eggs/Cython-0.29.26-py3.8-linux-x86_64.egg/Cython/Utils.py", line 55, in wrapper
        res = cache[args] = f(self, *args)
      File "/tmp/pip-req-build-1zndcudd/.eggs/Cython-0.29.26-py3.8-linux-x86_64.egg/Cython/Build/Dependencies.py", line 535, in included_files
        include_path = self.context.find_include_file(include, None)
      File "/tmp/pip-req-build-1zndcudd/.eggs/Cython-0.29.26-py3.8-linux-x86_64.egg/Cython/Compiler/Main.py", line 285, in find_include_file
        error(pos, "'%s' not found" % filename)
      File "/tmp/pip-req-build-1zndcudd/.eggs/Cython-0.29.26-py3.8-linux-x86_64.egg/Cython/Compiler/Errors.py", line 178, in error
        raise InternalError(message)
    Cython.Compiler.Errors.InternalError: Internal compiler error: 'sollya_settings.pxi' not found
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by nibrunie** [comment]
I think that you have not installed sollya.
Before installing pythonsollya, you need to install `sollya` and `libsollya-dev`

**Comment by nibrunie** [comment]
On ubuntu, you can try `sudo apt install sollya libsollya-dev`

**Comment by hbrunie** [comment]
Super, solved for me.
I only had to do 
`export PYTHONPATH=/home/hbrunie/github/metalibm/metalibm_core:$PYTHONPATH`
to execute without error the README.me command example:
`python3 metalibm_functions/ml_exp.py --precision binary64 --target x86_avx2 --output x86_avx2_exp_fp64.c`
Thanks
