### ISSUE TITLE
Unit tests failure

### ISSUE THREAD

**Issue by hbrunie** [metalibm/metalibm#108]
I had some unit tests failure:
`python valid/soft_unit_test.py`
I only copy paste here the failure I found in the output of this execution:
```

legalize_reciprocal_seed failure ! (0/1 success(es) inc. 1 unexpected failure(s))
    legalize_reciprocal_seed failed
[...]
embedded binary failure ! (0/2 success(es) inc. 2 unexpected failure(s))
    embedded binary failed
    embedded binary failed
bfloat16 success ! (1/1)
runtime error eval success ! (1/1)
special values success ! (1/1)
numerical simplification success ! (1/1)
basic machine code generation success ! (1/1)
asm loop generation success ! (1/1)
copysign failure ! (0/1 success(es) inc. 1 unexpected failure(s))
    copysign failed
arithmetic_right_shift failure ! (0/1 success(es) inc. 1 unexpected failure(s))
```

**Comment by nibrunie** [comment]
Could you run `python valid/soft_unit_test.py --debug` ?

**Comment by hbrunie** [comment]
Sure.
```
 >> python valid/soft_unit_test.py --debug
associating generator <class 'metalibm_core.code_generation.generators.llvm_ir_code_generator.LLVMIRCodeGenerator'> with language <class 'metalibm_core.code_generation.code_constant.LLVM_IR_Code'>
associating generator <class 'metalibm_core.code_generation.generators.c_code_generator.CCodeGenerator'> with language <class 'metalibm_core.code_generation.code_constant.C_Code'>
associating generator <class 'metalibm_core.code_generation.generators.c_code_generator.CCodeGenerator'> with language <class 'metalibm_core.code_generation.code_constant.OpenCL_Code'>
associating generator <class 'metalibm_core.code_generation.generators.asm_code_generator.AsmCodeGenerator'> with language <class 'metalibm_core.code_generation.code_constant.ASM_Code'>
initializing MPFR target
Traceback (most recent call last):
  File "valid/soft_unit_test.py", line 389, in <module>
    test_result = test_scheme.perform_all_test(debug = debug_flag)
  File "/home/hbrunie/github/metalibm/valid/test_utils.py", line 128, in perform_all_test
    result_list = self.perform_all_test_no_reduce(debug)
  File "/home/hbrunie/github/metalibm/valid/test_utils.py", line 95, in perform_all_test_no_reduce
    return [self.single_test(tc, debug=debug) for tc in self.argument_tc]
  File "/home/hbrunie/github/metalibm/valid/test_utils.py", line 95, in <listcomp>
    return [self.single_test(tc, debug=debug) for tc in self.argument_tc]
  File "/home/hbrunie/github/metalibm/valid/unit_test.py", line 76, in single_test
    runner(arg_template)
  File "/home/hbrunie/github/metalibm/metalibm_functions/unit_tests/legalize_reciprocal_seed.py", line 117, in run_test
    ml_ut_legalize_rcp.gen_implementation()
  File "/home/hbrunie/github/metalibm/metalibm_core/core/ml_function.py", line 788, in gen_implementation
    return self.build_and_execute_source_code(function_group, source_code, embedding_binary=embedding_binary)
  File "/home/hbrunie/github/metalibm/metalibm_core/core/ml_function.py", line 772, in build_and_execute_source_code
    execute_result = self.execute_output(embedding_binary, source_file)
  File "/home/hbrunie/github/metalibm/metalibm_core/core/ml_function.py", line 1022, in execute_output
    bin_file = source_file.build(self.processor, bin_name, shared_object=shared_object, link=link_trigger, extra_build_opts=self.get_extra_build_opts())
  File "/home/hbrunie/github/metalibm/metalibm_core/utility/build_utils.py", line 196, in build
    build_command = SourceFile.get_build_command(self.path, target, bin_name, shared_object, link, expand_env_var=True, extra_build_opts=extra_build_opts, library_list=self.library_list)
  File "/home/hbrunie/github/metalibm/metalibm_core/utility/build_utils.py", line 156, in get_build_command
    ML_SRC_DIR = "$ML_SRC_DIR" if not expand_env_var else os.environ["ML_SRC_DIR"]
  File "/usr/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'ML_SRC_DIR'

```

Then I updated the environment variable ML_SRC_DIR.

```
 >> python valid/soft_unit_test.py --debug
associating generator <class 'metalibm_core.code_generation.generators.llvm_ir_code_generator.LLVMIRCodeGenerator'> with language <class 'metalibm_core.code_generation.code_constant.LLVM_IR_Code'>
associating generator <class 'metalibm_core.code_generation.generators.c_code_generator.CCodeGenerator'> with language <class 'metalibm_core.code_generation.code_constant.C_Code'>
associating generator <class 'metalibm_core.code_generation.generators.c_code_generator.CCodeGenerator'> with language <class 'metalibm_core.code_generation.code_constant.OpenCL_Code'>
associating generator <class 'metalibm_core.code_generation.generators.asm_code_generator.AsmCodeGenerator'> with language <class 'metalibm_core.code_generation.code_constant.ASM_Code'>
initializing MPFR target
test successful undef_function
initializing MPFR target
undef.c:12:10: fatal error: papi.h: No such file or directory
   12 | #include <papi.h>
      |          ^~~~~~~~
compilation terminated.
Error: build failed: 

Traceback (most recent call last):
  File "valid/soft_unit_test.py", line 389, in <module>
    test_result = test_scheme.perform_all_test(debug = debug_flag)
  File "/home/hbrunie/github/metalibm/valid/test_utils.py", line 128, in perform_all_test
    result_list = self.perform_all_test_no_reduce(debug)
  File "/home/hbrunie/github/metalibm/valid/test_utils.py", line 95, in perform_all_test_no_reduce
    return [self.single_test(tc, debug=debug) for tc in self.argument_tc]
  File "/home/hbrunie/github/metalibm/valid/test_utils.py", line 95, in <listcomp>
    return [self.single_test(tc, debug=debug) for tc in self.argument_tc]
  File "/home/hbrunie/github/metalibm/valid/unit_test.py", line 76, in single_test
    runner(arg_template)
  File "/home/hbrunie/github/metalibm/metalibm_functions/unit_tests/embedded_bin.py", line 93, in __call__
    ml_ut_embedded_bin.gen_implementation()
  File "/home/hbrunie/github/metalibm/metalibm_core/core/ml_function.py", line 788, in gen_implementation
    return self.build_and_execute_source_code(function_group, source_code, embedding_binary=embedding_binary)
  File "/home/hbrunie/github/metalibm/metalibm_core/core/ml_function.py", line 772, in build_and_execute_source_code
    execute_result = self.execute_output(embedding_binary, source_file)
  File "/home/hbrunie/github/metalibm/metalibm_core/core/ml_function.py", line 1025, in execute_output
    Log.report(Log.Error, "build failed: \n", error=BuildError())
  File "/home/hbrunie/github/metalibm/metalibm_core/utility/log_report.py", line 131, in report
    raise error or Exception(msg.format(*args, **kw))
metalibm_core.core.ml_function.BuildError

```

On Ubuntu `sudo apt-get install papi-tools` is not enough to correct the error of `papi.h not found`.

**Comment by nibrunie** [comment]
you need `sudo apt install libpapi-dev` and to set `ML_SRC_DIR`
`export ML_SRC_DIR=/home/hbrunie/github/metalibm/`

**Comment by hbrunie** [comment]
Thank you!
The output of `python valid/soft_unit_test.py --debug` is 
```
[...]
OVERALL SUCCESS
```

**Comment by hbrunie** [comment]
Thus it was only due to the `ML_SRC_DIR` env var not set.
